server:
  port: 8080
  servlet:
    context-path: /
spring:
  application:
    name: LiZhuangShopping
  datasource:
    username: root
    password: "root1234"
    url: jdbc:mysql://127.0.0.1:3306/shopping_vx?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  configuration:
    map-underscore-to-camel-case: false
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mybatis/mapper/*.xml